services:
  db:
    image: postgres:16
    container_name: achpet-db
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: achpet
    ports:
      - "5432:5432"
    volumes:
      - achpet_db:/var/lib/postgresql/data

volumes:
  achpet_db:
